import './globals.css'
import { Inter } from 'next/font/google'
import TopNavBar from '@components/TopNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <header>
        <TopNavBar />
      </header>
        <main className={inter.className}>{children}</main> 
      </body>
    </html>
  )
}
